[package]
name = "imt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.7"
hex = "0.4.3"
sha256 = "1.5.0"
thiserror = "1.0.41"
